# Site settings
title: GDG VIT - Project Ideas
email: gdgvitvellore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Google Developers Groups was established in VIT on 28th July 2014 and since then 3 successful events were conducted .
 The group now has 60 Developers ,This groups’s agenda is to introduce new technologies to the students, develop new ideas and polish skills in every possible field including management our faculty coordinator is Prof .P Senthilnathan and has guided us along this journey.

baseurl: "/jobs" # the subpath of your site, e.g. /blog/
url: "http://gdgvitvellore.com/" # the base hostname & protocol for your site
twitter_username: gdgvitvellore
github_username:  gdgvit
google_play: '9033840087167154769'
google_plus_com: '101018908043689071742'  # Community link
google_plus_per: '+gdgvitvellore'  #Personal link

# Build settings
markdown: kramdown
permalink: /:month-:day-:year/:title.html

kramdown:
  input: GFM
